on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to github docker registry
              run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Build and push Docker image
              run: |
                  docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/juanpablocs/my-nginx:latest --push .
    deploy:
        needs: create-docker-image
        runs-on: ubuntu-latest
        steps:
            - name: Install sshpass
              run: sudo apt-get install -y sshpass
            
            - name: Deploy to server
              run: |
                sshpass -p '${{ secrets.SSH_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
                    docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_GITHUB }}
                    docker pull ghcr.io/juanpablocs/my-nginx:latest
                    docker stop my-nginx || true
                    docker rm my-nginx || true
                    docker run -d --name my-nginx -p 80:80 --restart always ghcr.io/juanpablocs/my-nginx:latest
                EOF
